name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore backend/Secon_SBTi_API.sln

      - name: Build
        run: dotnet build backend/Secon_SBTi_API_solution/Secon_SBTi_API.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test backend/Secon_SBTi_API_solution/Secon_SBTi_API.sln --no-build --configuration Release
